package com.walter.mapper.mbg;

import com.walter.domain.mbg.MbgDepartment;
import com.walter.domain.mbg.MbgDepartmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MbgDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Sun Sep 15 18:55:16 CST 2019
     */
    long countByExample(MbgDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Sun Sep 15 18:55:16 CST 2019
     */
    int deleteByExample(MbgDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Sun Sep 15 18:55:16 CST 2019
     */
    int insert(MbgDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Sun Sep 15 18:55:16 CST 2019
     */
    int insertSelective(MbgDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Sun Sep 15 18:55:16 CST 2019
     */
    List<MbgDepartment> selectByExample(MbgDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Sun Sep 15 18:55:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") MbgDepartment record, @Param("example") MbgDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Sun Sep 15 18:55:16 CST 2019
     */
    int updateByExample(@Param("record") MbgDepartment record, @Param("example") MbgDepartmentExample example);
}