package com.walter.mapper.mbg;

import com.walter.domain.mbg.MbgEmployee;
import com.walter.domain.mbg.MbgEmployeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MbgEmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Sun Sep 15 18:55:16 CST 2019
     */
    long countByExample(MbgEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Sun Sep 15 18:55:16 CST 2019
     */
    int deleteByExample(MbgEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Sun Sep 15 18:55:16 CST 2019
     */
    int insert(MbgEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Sun Sep 15 18:55:16 CST 2019
     */
    int insertSelective(MbgEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Sun Sep 15 18:55:16 CST 2019
     */
    List<MbgEmployee> selectByExample(MbgEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Sun Sep 15 18:55:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") MbgEmployee record, @Param("example") MbgEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Sun Sep 15 18:55:16 CST 2019
     */
    int updateByExample(@Param("record") MbgEmployee record, @Param("example") MbgEmployeeExample example);
}